name: NusantaraScript
version: ${project.version}
main: com.crow6980.nusantarascript.NusantaraScript
api-version: '1.16'
author: crow6980
description: Indonesian Language Scripting for Minecraft

commands:
  nusantara:
    description: Main command for NusantaraScript
    usage: /nusantara <reload|list|info>
    aliases: [ns, nscript]
    permission: nusantarascript.admin

permissions:
  nusantarascript.admin:
    description: Access to all NusantaraScript commands
    default: op
